apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset
  namespace: argoexamples
spec:
  generators:
  - pullRequest:
      github:
        owner: "dwillett"
        repo: "argocd-example-apps"
      requeueAfterSeconds: 300
  template:
    metadata:
      name: 'appset-app-{{branch}}-{{number}}'
    spec:
      destination:
        namespace: 'helm-guestbook-{{branch}}-{{number}}'
        server: https://kubernetes.default.svc
      project: default
      source:
        path: helm-guestbook
        repoURL: https://github.com/dwillett/argocd-example-apps
        targetRevision: '{{head_sha}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
