---
apiVersion: v1
kind: Secret
metadata:
  name: github-token
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
type: Opaque
data:
  token: "Z2hwX3lheUVZbEZHTENLQTV0N2pvY3M3cm9NZ3FWTU5zbzN1bVJORQ=="