---
apiVersion: v1
kind: Secret
metadata:
  name: github-token
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
type: Opaque
data:
  token: Z2hwX0owWmw0Sjc4ajNMZWVpeVJNNDN1STRQdUtPcTVkbjFCQmxWZQ==