apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset
  namespace: argoexamples
spec:
  generators:
  - pullRequest:
      github:
        owner: "dwillett"
        repo: "argocd-example-apps"
        labels:
        - "argo"
      requeueAfterSeconds: 300
  template:
    metadata:
      name: 'appset-app-{{`{{branch}}`}}-{{`{{number}}`}}'
    spec:
      destination:
        namespace: 'helm-guestbook-{{`{{branch}}`}}-{{`{{number}}`}}'
        server: {{ .Values.spec.destination.server }}
      project: default
      source:
        path: helm-guestbook
        repoURL: {{ .Values.spec.source.repoURL }}
        targetRevision: '{{`{{head_sha}}`}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
