---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: sockshopfrontend
spec:
  entryPoints:
  - web
  routes:
    - kind: Rule
      match: Host(`sockshop.local.willett.rocks`)
      services:
        - kind: Service
          name: front-end
          namespace: argoexamples
